tests=(
"file"
"file[Ghalkjoai9sdjoakjl]"
"file[as,.md-sldjfnslJGlfk983uj-sdfkj&hkjdh]"
"file[a-b]"
"file[b-a]"
"file[-ab2]"
"file[1-2-]"
"file[1-9a-gGB]"
"file[1-9a-g]?"
"file[B9-1Gg-ae]"
"file[10-1]"
'file[\"1-G\"]'
"file'[1-G]'"
#"file[!'1'-'9k]'\"D\"-G]"
"file[!2-9]"
"file[^2-9]"
"file[!9-2]"
"file[^9-2]"
"file[!hfksdhkfjhsk!sljlsj]"
"file[]"
"file[]9-1GF\\']"
"file[\\\"\\']"
"file[]]"
"file[[]"
"file[[]]"
"file[]\]\]\]]"
"file[-]"
"file[---]"
"file[--]"
"file[!ag][0]"
"file[''']'"
"file[\\'\\'']'"
"[]file1"
"file[902]"
"file\\\"[902]"
"file[-8-H]"
"file[H-h]"
"file[?*]"
"file\[2]"
"file[\\]"
"file[\^7]"
"*e"
"*e*"
"*e*??"
"*e*???????????????????"
"?file"
"*file"
"fi*le[2-L][0-8jdfh]"
"file[[:alnum:]]"
"file[[:alpha:]]"
"file[[:ascii:]]"
"file[[:blank:]]"
"file[[:cntrl:]]"
"file[[:digit:]]"
"file[[:graph:]]"
"file[[:lower:]]"
"file[[:print:]]"
"file[[:punct:]]"
"file[[:space:]]"
"file[[:upper:]]"
"file[[:word:]]"
"file[^[:xdigit:]]"
"file[^[:alnum:]]"
"file[^[:alpha:]]"
"file[^[:ascii:]]"
"file[^[:blank:]]"
"file[^[:cntrl:]]"
"file[^[:digit:]]"
"file[^[:graph:]]"
"file[^[:lower:]]"
"file[^[:print:]]"
"file[^[:punct:]]"
"file[^[:space:]]"
"file[^[:upper:]]"
"file[^[:word:]]"
"file[^[:xdigit:]]"
"file[[::]]"
"file[[:]]"
"file[^[::]"
"file[::]]"
"file[[:digit:]][[:digit:]]"
"file[][][][][][][][][][][][]["
"file[:digit:]"
"file[[:jslkdf:]]"
"file\[[[:graph:]]"
"file[:"
"fi*le[:dsdf:]"
"?file"
"file?"
"file*"
"file[[:digit:][:alpha:][:space:]]"
"file[![:digit:][:alpha:][:space:]]"
"file[^[:digit:][:alpha:][:space:]]"
'file\\*'
'file[\\[:digit:]]'
'fi\\le\\?'
'file\\[]'
'file[]]'
'file[!]]'
'file[^]]'
'file[]-[]'
'file[\\]'
'file[\]'
'file[:space]]'
'file[[[:digit:]]'
'file[^[[:digit:]'
'"file"'
'"file["l]'
'file["]"'
#'file["[:"word:]]'
'file[\"]'
'file[\"]""'
'file[[:xdigit'
'file[[:print\:]]'
'file[[:print\\:]]'
'file[[:pun"c"t:]]'
'fil'
'file[[:blank:]\ ]]'
'file[[:blank:]\\ ]]'
'file[]]'
)